
_target_: "rl_lib.algs.dqn.DQN"
lr: 0.0023
replay_size: 100000
target_update_interval: 10
update_freq: 256
gradient_steps: 128
minibatch_size: 64
gamma: 0.99
warmup_steps: 1000
cgn: 10.0
load_path:

epsilon_scheduler:
  type: "linear"
  params:
    start_value: 1.0
    end_value: 0.04
    steps: 8000

net_architecture:
  enc:
    type: "MLP"
    layers:
      - type: "LINEAR"
        in: "IN"
        out: 256
        activation: "RELU"
      - type: "LINEAR"
        in: 256
        out: 256
        activation: "RELU"

  # enc:
  #   type: "CNN"
  #   layers:
  #     - type: "CONV"
  #       in: "IN"
  #       out: 16
  #       kernel: 8
  #       stride: 4
  #       activation: "RELU"
  #     - type: "CONV"
  #       in: 16
  #       out: 32
  #       kernel: 4
  #       stride: 2
  #       activation: "RELU"
  #     - type: "FLATTEN"
  #     - type: "LINEAR"
  #       in: 2592
  #       out: 256
  #       activation: "RELU"