
_target_: "rl_lib.algs.ppo.PPO"
lr: 0.001
tmax: 32
gamma: 0.99
lam: 0.8
epochs: 20
minibatch_size: 256
epsilon: 0.2
entropy_weight: 0.0
cgn: 0.5
value_weight: 0.5
load_path:

net_architecture:
  # shared_enc:
  #   type: "CNN"
  #   layers:
  #     - type: "CONV"
  #       in: "IN"
  #       out: 16
  #       kernel: 8
  #       stride: 4
  #       activation: "RELU"
  #     - type: "CONV"
  #       in: 16
  #       out: 32
  #       kernel: 4
  #       stride: 2
  #       activation: "RELU"
  #     - type: "FLATTEN"
  #     - type: "LINEAR"
  #       in: 2592
  #       out: 256
  #       activation: "RELU"

  # shared_enc:
  #   type: "MLP"
  #   layers:
  #     - type: "LINEAR"
  #       in: "IN"
  #       out: 64
  #       activation: "TANH"
  #     - type: "LINEAR"
  #       in: 64
  #       out: 64
  #       activation: "TANH"
  actor_enc:
    type: "MLP"
    layers:
      - type: "LINEAR"
        in: "IN"
        out: 64
        activation: "TANH"
      - type: "LINEAR"
        in: 64
        out: 64
        activation: "TANH"
  value_enc:
    type: "MLP"
    layers:
      - type: "LINEAR"
        in: "IN"
        out: 64
        activation: "TANH"
      - type: "LINEAR"
        in: 64
        out: 64
        activation: "TANH"