
_target_: "rl_lib.algs.ppo.PPO"
lr: 0.001
tmax: 64

net_architecture:
  shared_enc:
    type: "MLP"
    layers:
      - type: "LINEAR"
        in: "IN"
        out: 64
        activation: "TANH"
      - type: "LINEAR"
        in: 64
        out: 64
        activation: "TANH"
    
